[project]
name = "global-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.6",
    "ruff>=0.11.11",
    "torch>=2.7.0",
]

