name: ruff-lint-check
on:
  push:
    branches:
      - dev
      - testing
      - wip
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff Lint Check
        run: ruff check --output-format=github .

      - name: Run Format Check
        run: ruff format --check --diff .
